### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by tomas-pluskal** [magarveylab/prism-releases#1]
Hi,

I would like to try running PRISM on our own server, because your web interface is limited to 50 MB FASTA files. I cloned the repo and tried to compile with maven, but it says:

````
[ERROR] Failed to execute goal on project prism: Could not resolve dependencies for project ca.mcmaster.magarveylab.prism:prism:war:1.0.0-SNAPSHOT: Could not find artifact ca.mcmaster.magarveylab.wasp:wasp:jar:0.0.1-SNAPSHOT -> [Help 1]
````

I would appreciate your help.

Tomas

**Comment by nishanthmerwin** [comment]
Hi Tomas,

Right now, PRISM isn't set up to compile via maven (the pom.xml file in there is misleading, we tried at one point but never pursued getting it fully "maven-able").
The wasp.jar file is actually within the lib directory (/prism/lib/wasp.jar).

Are you trying to deploy the WAR onto your own tomcat webserver? Or are you just trying to run PRISM from the command line?

For simply running a 50mb fasta file, I'd recommend using the pre-compiled release version here:
https://github.com/magarveylab/prism-releases/releases/download/v2.1.5/prism-2.1.5.jar.

You can then upload the resulting json report to our server for viewing.

**Comment by tomas-pluskal** [comment]
Thanks for the quick response!

I think command line is sufficient for me. I'll use the release version, as you suggest. Are you planning to release the v.3 anytime soon?

**Comment by tomas-pluskal** [comment]
So, I'm trying to recompile prism from sources, because there seems to be no other way to remove the 50 MB limit. 
````
javac -cp "lib/*:lib/lib/*" `find src -name *.java`
````
It says the "enum" package is missing:
````
src/ca/mcmaster/magarveylab/prism/data/Cyclization.java:36: error: cannot find symbol
	public CyclizationPatterns type() {
	       ^
  symbol:   class CyclizationPatterns
  location: class Cyclization
src/ca/mcmaster/magarveylab/prism/cluster/analysis/DomainAnalyzer.java:6: error: package ca.mcmaster.magarveylab.enums does not exist
import ca.mcmaster.magarveylab.enums.CStarterSubstrates;
                                    ^
src/ca/mcmaster/magarveylab/prism/cluster/analysis/DomainAnalyzer.java:7: error: package ca.mcmaster.magarveylab.enums does not exist
import ca.mcmaster.magarveylab.enums.DomainFamilies;
                                    ^
````

**Comment by tomas-pluskal** [comment]
Nevermind, found it! https://github.com/magarveylab/enums-releases

**Comment by tomas-pluskal** [comment]
By the way, it would make sense to include the enums in the prism release jar, since you are anyway creating an uber-jar and adding all dependencies into it.

**Comment by nishanthmerwin** [comment]
Just comment out these lines when you build it, and it should work for your file.

[https://github.com/magarveylab/prism-releases/blob/master/prism/src/ca/mcmaster/magarveylab/prism/Prism.java#L135-L137](https://github.com/magarveylab/prism-releases/blob/master/prism/src/ca/mcmaster/magarveylab/prism/Prism.java#L135-L137)

**Comment by tomas-pluskal** [comment]
Thanks, I got it working!
