### ISSUE TITLE
cdps hmm availability

### ISSUE THREAD

**Issue by charles-bernard** [magarveylab/prism-releases#10]
Hi,

I've just read your paper about your genome mining of CDPS, and I've seen that you have built hmm profiles based on the studies of Jacques et al. I've cloned this repository with the hope to find them into but I haven't... Do you plan to integrate them in this repository any time soon? Otherwise, would you be as kind as to send them to me by email? 

Best,

Charles

**Comment by stlang** [comment]
Hi Charles,

All publicly available information is available here in the repository. An up to date PRISM web server is provided with the latest published version, including CDPS.

We are aware that the web server had been down since the start of the year, but it is once again live!

Best,

Chris
