### ISSUE TITLE
No PRISM3 release jar?

### ISSUE THREAD

**Issue by dswan** [magarveylab/prism-releases#9]
The PRISM releases page only goes up to 2.1.5:

https://github.com/magarveylab/prism-releases/releases

From the website:

"December 31, 2016 PRISM 3 is online now. We're rolling out some big changes with PRISM 3"

Are there plans to release a build for PRISM 3?

**Comment by skinnider** [comment]
Unfortunately, at present PRISM 3 is released as a web application only.
